/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as mocks from "./mocks";
export type { mocks };
export type { IMessageV3 } from "./IMessageV3";
export type { MessageV3ClientUpgradeable } from "./MessageV3ClientUpgradeable";
export type { SimpleNFT } from "./SimpleNFT";
