/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IMessageV3,
  IMessageV3Interface,
} from "../../../contracts/MessageTest.sol/IMessageV3";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "recipient",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "chain",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
      {
        internalType: "uint16",
        name: "confirmations",
        type: "uint16",
      },
      {
        internalType: "bool",
        name: "express",
        type: "bool",
      },
    ],
    name: "sendMessage",
    outputs: [
      {
        internalType: "uint256",
        name: "txId",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "signer",
        type: "address",
      },
    ],
    name: "setExsig",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IMessageV3__factory {
  static readonly abi = _abi;
  static createInterface(): IMessageV3Interface {
    return new Interface(_abi) as IMessageV3Interface;
  }
  static connect(address: string, runner?: ContractRunner | null): IMessageV3 {
    return new Contract(address, _abi, runner) as unknown as IMessageV3;
  }
}
