/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IMessageV3__factory } from "./IMessageV3__factory";
export { MessageTest__factory } from "./MessageTest__factory";
