/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IClient,
  IClientInterface,
} from "../../../contracts/MessageV3.sol/IClient";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "txId",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "sourceChainId",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "sender",
        type: "address",
      },
      {
        internalType: "address",
        name: "recipient",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "messageProcess",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IClient__factory {
  static readonly abi = _abi;
  static createInterface(): IClientInterface {
    return new Interface(_abi) as IClientInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IClient {
    return new Contract(address, _abi, runner) as unknown as IClient;
  }
}
