/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as mockWethSol from "./MockWETH.sol";
export type { mockWethSol };
export type { MockToken } from "./MockToken";
